export interface GrammarRuleData {
  id: string;
  name: string;
  description: string;
  level: "A1" | "A2" | "B1" | "B2" | "C1";
  explanation: string;
  examples: string;
  tips?: string;
  order: number;
}

export const grammarRules: GrammarRuleData[] = [
  // ===== A1 =====
  { id: "a1-01", name: "Personalpronomen", description: "Ich, du, er, sie, es, wir, sie, Sie", level: "A1", order: 1,
    explanation: "Die Personalpronomen stehen am Anfang des Satzes und geben an, wer die Handlung ausführt. 'Sie' (großgeschrieben) ist die höfliche Form.",
    examples: "Ich bin Student. | Du bist nett. | Er liest ein Buch. | Sie kommt aus der Türkei. | Es regnet. | Wir gehen in die Schule. | Sie (pl.) lernen Deutsch. | Sie (Höflichkeit) sind mein Lehrer.", tips: "Im Deutschen gibt es drei Formen von 'sie': sie (er), sie (sie pl.), Sie (Höflichkeit). Achte auf die Groß-/Kleinschreibung!" },
  { id: "a1-02", name: "Verben sein und haben", description: "Die wichtigsten unregelmäßigen Verben im Präsens", level: "A1", order: 2,
    explanation: "Das Verb 'sein' (to be) und 'haben' (to have) sind die häufigsten Verben im Deutschen. Sie sind unregelmäßig und müssen auswendig gelernt werden.",
    examples: "ich bin, du bist, er/sie ist, wir sind, sie sind, Sie sind | ich habe, du hast, er/sie hat, wir haben, sie haben, Sie haben", tips: "Merke: 'Ich bin' und 'Du bist' – das sind die häufigsten Fehler bei Anfängern!" },
  { id: "a1-03", name: "Regelmäßige Verben im Präsens", description: "Verbkonjugation mit -e, -st, -t, -en, -t, -en", level: "A1", order: 3,
    explanation: "Die meisten Verben folgen einem regelmäßigen Muster: ich mach-e, du mach-st, er/sie mach-t, wir mach-en, sie mach-t, Sie mach-en.",
    examples: "machen: ich mache, du machst, er macht, wir machen, sie machen | lernen: ich lerne, du lernst, er lernt | spielen: ich spiele, du spielst, er spielt", tips: "Bei Verben mit -eln (z.B. 'handeln'): ich handel-e → ich handel (ohne e!). Bei Verben mit -ten (z.B. 'arbeiten'): du arbeitest." },
  { id: "a1-04", name: "Unregelmäßige Verben", description: "Wichtige Verben mit Vokalwechsel", level: "A1", order: 4,
    explanation: "Einige Verben ändern den Vokal in der du- und er/sie-Form: fahren → fährst/fährt, schlafen → schläfst/schläft, nehmen → nimmst/nimmt.",
    examples: "fahren: ich fahre, du fährst, er fährt | lesen: ich lese, du liest, er liest | geben: ich gebe, du gibst, er gibt | nehmen: ich nehme, du nimmst, er nimmt", tips: "Vokalwechsel: a→ä, e→i, o→ö. Nicht alle Verben ändern den Vokal – prüfe immer!" },
  { id: "a1-05", name: "Verneinung mit nicht und kein", description: "Negation von Verben, Nomen und Adjektiven", level: "A1", order: 5,
    explanation: "Verben werden mit 'nicht' verneint: Ich komme nicht. Nomen mit 'kein/keine': Ich habe keinen Hund. Bei 'sein' + Adjektiv: Das ist nicht gut.",
    examples: "Ich komme nicht. | Das ist nicht gut. | Ich habe keinen Hund. | Ich habe keine Zeit. | Das ist kein Problem.", tips: "'nicht' steht am Satzende oder vor dem Verbstamm. 'kein' ersetzt 'ein/eine' bei verneinten Nomen." },
  { id: "a1-06", name: "Bestimmte Artikel", description: "der, die, das – Maskulin, Feminin, Neutral", level: "A1", order: 6,
    explanation: "Jedes deutsche Nomen hat einen Artikel: der (maskulin), die (feminin), das (neutral). Der Artikel zeigt das Genus an.",
    examples: "der Mann, die Frau, das Kind | der Tisch, die Lampe, das Buch | der Hund, die Katze, das Haus", tips: "Es gibt keine einfache Regel für das Genus. Am besten: Nomen IMMER mit dem Artikel lernen! Tipp: Farbige Karteikarten (rot=maskulin, blau=feminin, grün=neutral)." },
  { id: "a1-07", name: "Unbestimmte Artikel", description: "ein, eine – wie bestimmte Artikel, aber ohne Bestimmtheit", level: "A1", order: 7,
    explanation: "Der unbestimmte Artikel entspricht 'einer/einem' im Deutschen. er hat die gleiche Form wie der bestimmte Artikel, nur ohne bestimmte Form.",
    examples: "ein Mann, eine Frau, ein Kind | ein Tisch, eine Lampe, ein Buch | ein roter Apfel, eine große Wohnung", tips: "Kein Artikel (Nullartikel): Bei Berufen, Sprachen, Mahlzeiten: Er ist Lehrer. Sie spricht Deutsch. Wir essen Frühstück." },
  { id: "a1-08", name: "Possessivartikel", description: "mein, dein, sein, ihr – Possessivpronomen", level: "A1", order: 8,
    explanation: "Possessivartikel zeigen Zugehörigkeit an: mein (my), dein (his), sein (his), ihr (her), unser (our), euer (your pl.), ihr (their), Ihr (your formal).",
    examples: "das ist mein Buch. | Das ist dein Stuhl. | Das ist sein Auto. | Das ist ihre Tasche. | Das ist unser Haus. | Das ist euer Kind.", tips: "Possessivartikel werden wie 'ein' dekliniert: mein→meinen (Akk.), mein→meinem (Dat.), mein→meines (Gen.)." },
  { id: "a1-09", name: "Pluralbildung der Nomen", description: "Verschiedene Pluralformen", level: "A1", order: 9,
    explanation: "Der Plural im Deutschen hat verschiedene Formen: -e (Tische), -er (Kinder), -er (Mädchen), -en (Frauen), -n (Lehrern), -s (Autos), Umlaut (Ärzte) oder keine Änderung.",
    examples: "der Tisch → die Tische | das Kind → die Kinder | die Frau → die Frauen | der Arzt → die Ärzte | das Auto → die Autos", tips: "Der Plural hat IMMER den Artikel 'die'. Merke die Pluralform zusammen mit dem Nomen!" },
  { id: "a1-10", name: "Satzbau: Hauptsatz", description: "Subjekt + Verb + Objekt (Teekannenregel)", level: "A1", order: 10,
    explanation: "Im Hauptsatz steht das Verb an zweiter Stelle (Position 2). Das Subjekt steht auf Position 1 oder 3.",
    examples: "Ich lerne Deutsch. | Deutsch lerne ich. (Betonung) | Heute lerne ich Deutsch. | Morgen gehe ich in die Schule.", tips: "Die 'Teekannenregel': Auf Position 1 steht eine Zeitangabe oder ein anderes Wort, auf Position 2 steht das Verb." },
  { id: "a1-11", name: "Fragewörter", description: "Wer, was, wo, wann, wie, warum, wie viel", level: "A1", order: 11,
    explanation: "Fragewörter stehen am Anfang des Satzes. Das Verb steht direkt danach (wie im Nebensatz).",
    examples: "Wer bist du? | Was machst du? | Wo wohnst du? | Wann kommst du? | Wie geht es dir? | Warum lernst du Deutsch? | Wie viel kostet das?", tips: "Der Unterschied zwischen 'wo' und 'wohin': Wo? (Ort) → Wo ist der Bahnhof? Wohin? (Richtung) → Wohin gehst du?" },
  { id: "a1-12", name: "Präpositionen: in, an, auf, mit, von, zu", description: "Wichtige Präpositionen mit Dativ oder Akkusativ", level: "A1", order: 12,
    explanation: "Einige Präpositionen verlangen den Dativ (mit, von, zu, aus, bei, nach, seit) andere den Akkusativ (durch, für, gegen, ohne, um).",
    examples: "Ich gehe mit dem Bus. (Dativ) | Das Buch ist von dir. (Dativ) | Ich gehe in die Schule. (Akk.) | Das ist für dich. (Akk.)", tips: "Dativ-Präpositionen: aus, bei, mit, nach, seit, von, zu. Akkusativ-Präpositionen: durch, für, gegen, ohne, um." },
  { id: "a1-13", name: "Dativ vs. Akkusativ", description: "Wann benutzt man welchen Kasus?", level: "A1", order: 13,
    explanation: "Akkusativ: Direktes Objekt (wen? was?). Dativ: Indirektes Objekt (wem?). Präpositionen bestimmen den Kasus.",
    examples: "Ich sehe den Mann. (Akk.) | Ich gebe dem Mann das Buch. (Dat.) | Ich kaufe eine Blume. (Akk.) | Ich kaufe dem Kind eine Blume. (Dat.)", tips: "Tipp: Nach 'möchten' oder 'gerne' steht der Akkusativ: Ich hätte gerne einen Kaffee." },
  { id: "a1-14", name: "Modalverben", description: "können, müssen, wollen, sollen, dürfen, mögen", level: "A1", order: 14,
    explanation: "Modalverben stehen vor dem Hauptverb (Infinitiv). Das Hauptverb steht am Satzende. Die Konjugation folgt dem Muster des zweiten Person (du).",
    examples: "Ich kann Deutsch sprechen. | Du musst lernen. | Er will nach Hause gehen. | Wir sollen warten. | Sie darf nicht rauchen. | Ich mag Kaffee.", tips: "Bei Modalverben mit 'ich' fehlt oft das -e: ich kann (nicht: ich kann), ich muss (nicht: ich muss), ich soll (nicht: ich soll), ich darf (nicht: ich darf), ich mag (nicht: ich mag)." },
  { id: "a1-15", name: "Konnektoren: und, aber, oder, denn, weil", description: "Wichtige Konnektoren für Satzverbindungen", level: "A1", order: 15,
    explanation: "'und', 'aber', 'oder' stehen zwischen zwei Hauptsätzen. 'weil' und 'denn' leiten einen Nebensatz ein (Verb am Ende bei 'weil', direkt nach Konjunktion bei 'denn').",
    examples: "Ich lerne Deutsch und Englisch. | Ich gehe nicht, aber ich bleibe zu Hause. | Kaffee oder Tee? | Ich gehe nicht, weil ich krank bin. | Ich gehe nicht, denn ich bin krank.", tips: "'weil' – Verb am Satzende! 'denn' – Verb direkt nach 'denn' (wie im Hauptsatz)." },

  // ===== A2 =====
  { id: "a2-01", name: "Perfekt mit haben", description: "Das Perfekt bildet die vergangene Zeit im gesprochenen Deutsch", level: "A2", order: 16,
    explanation: "Das Perfekt besteht aus 'haben' (konjugiert) + Partizip II. Die meisten Verben bilden das Perfekt mit 'haben'.",
    examples: "Ich habe gelernt. | Du hast gegessen. | Er hat gearbeitet. | Wir haben gespielt. | Sie haben gelesen.", tips: "Das Partizip II steht am Satzende. Bei trennbaren Verben: ge- + Wortstamm + -t/-en: einkaufen → eingekauft." },
  { id: "a2-02", name: "Perfekt mit sein", description: "Bewegungsverben und Zustandsveränderungen", level: "A2", order: 17,
    explanation: "Bewegungsverben (gehen, fahren, kommen, laufen) und Zustandsveränderungen (aufwachen, einschlafen, sterben, werden) bilden das Perfekt mit 'sein'.",
    examples: "Ich bin gegangen. | Er ist gefahren. | Wir sind angekommen. | Sie ist aufgewacht. | Das Baby ist eingeschlafen.", tips: "Merke: Mit 'sein': gehen, fahren, kommen, laufen, fliegen, schwimmen, wandern, einsteigen, aussteigen, ankommen, abreisen, aufwachen, einschlafen, sterben, werden." },
  { id: "a2-03", name: "Plusquamperfekt", description: "Das Perfekt der Vergangenheit", level: "A2", order: 18,
    explanation: "Das Plusquamperfekt (Vergangenheit) wird gebildet mit: hatte/war + Partizip II. Es wird benutzt, um eine Handlung zu beschreiben, die vor einer anderen stattfand.",
    examples: "Ich hatte gegessen, bevor ich kam. | Er war gegangen, als ich ankam. | Wir hatten bereits gelernt, als der Lehrer kam.", tips: "Plusquamperfekt mit hatte: Die meisten Verben. Plusquamperfekt mit war: Bewegungsverben und Zustandsveränderungen." },
  { id: "a2-04", name: "Futur I", description: "Zukunftsform mit werden + Infinitiv", level: "A2", order: 19,
    explanation: "Das Futur I wird gebildet mit: werden (konjugiert) + Infinitiv am Satzende. Es drückt eine zukünftige Handlung aus oder eine Vermutung.",
    examples: "Ich werde morgen kommen. | Er wird nächstes Jahr studieren. | Wir werden um 8 Uhr abfahren.", tips: "Futur I wird oft durch das Präsens mit Zeitangaben ersetzt: Ich komme morgen." },
  { id: "a2-05", name: "Komparativ und Superlativ", description: "Vergleichsformen von Adjektiven", level: "A2", order: 20,
    explanation: "Komparativ: -er (groß → größer). Superlativ: am + -sten (am größten). Bei Adjektiven auf -el, -er fällt das -e- weg (dunkel → dunkler).",
    examples: "groß → größer → am größten | klein → kleiner → am kleinsten | gut → besser → am besten | schlecht → schlechter → am schlechtesten", tips: "Unregelmäßig: gut → besser → am besten, viel → mehr → am meisten, gern → lieber → am liebsten." },
  { id: "a2-06", name: "Reflexive Verben", description: "Verben mit sich (Akkusativ oder Dativ)", level: "A2", order: 21,
    explanation: "Reflexive Verben verwenden ein Reflexivpronomen: sich (Akk.) oder sich (Dat.). Das Pronomen passt sich dem Subjekt an.",
    examples: "Ich freue mich. (Akk.) | Du ärgert dich. (Akk.) | Er wäscht sich. (Akk.) | Wir sehen uns. (Akk.) | Ich dusche mir die Haare. (Dat.)", tips: "Akkusativ: sich (mich, dich, sich, uns, euch, sich). Dativ: sich (mir, dir, sich, uns, euch, sich)." },
  { id: "a2-07", name: "Akkusativ-Präpositionen", description: "durch, für, gegen, ohne, um", level: "A2", order: 22,
    explanation: "Diese Präpositionen verlangen immer den Akkusativ: durch (through), für (for), gegen (against), ohne (without), um (around/about).",
    examples: "Ich gehe durch den Park. | Das ist für dich. | Er rennt gegen den Wind. | Ohne dich kann ich nicht. | Um 3 Uhr komme ich.", tips: "'um' + Akkusativ für Uhrzeiten: um 10 Uhr. 'gegen' für Richtungen oder Ziele." },
  { id: "a2-08", name: "Dativ-Präpositionen", description: "aus, bei, mit, nach, seit, von, zu", level: "A2", order: 23,
    explanation: "Diese Präpositionen verlangen immer den Dativ: aus (from), bei (at/near), mit (with), nach (after/to), seit (since), von (from/of), zu (to).",
    examples: "Ich komme aus der Türkei. | Ich bin bei der Arbeit. | Das ist mit meinem Freund. | Nach der Schule gehe ich. | Seit gestern bin ich krank.", tips: "Dativ-Artikel: dem (maskulin), der (feminin), dem (neutral), den/dem (Plural)." },
  { id: "a2-09", name: "Wechselpräpositionen", description: "in, an, auf, über, unter, vor, hinter, neben, zwischen", level: "A2", order: 24,
    explanation: "Wechselpräpositionen verlangen den Akkusativ (Richtung/Ziel) oder den Dativ (Ort). Fragetests: Wohin? → Akkusativ. Wo? → Dativ.",
    examples: "Ich gehe in die Schule. (Akk.) | Ich bin in der Schule. (Dat.) | Ich stelle das auf den Tisch. (Akk.) | Das Buch liegt auf dem Tisch. (Dat.)", tips: "Wohin? → Akkusativ (Bewegung). Wo? → Dativ (statischer Ort)." },
  { id: "a2-10", name: "Konnektoren: weil, dass, wenn, als, obwohl", description: "Nebensatzkonjunktionen", level: "A2", order: 25,
    explanation: "'weil' (because), 'dass' (that), 'wenn' (if/when), 'als' (when – Vergangenheit), 'obwohl' (although) leiten einen Nebensatz ein (Verb am Ende).",
    examples: "Ich gehe nicht, weil ich krank bin. | Ich weiß, dass du Recht hast. | Wenn es regnet, bleibe ich zu Hause. | Als ich jung war, spielte ich viel. | Obwohl es regnet, gehe ich.", tips: "'als' nur für einmaliges Ereignis in der Vergangenheit. 'wenn' für wiederholte Ereignisse oder hypothetische Situationen." },
  { id: "a2-11", name: "Relativsätze", description: "Sätze mit der, die, das, denen", level: "A2", order: 26,
    explanation: "Relativsätze geben zusätzliche Informationen über ein Nomen. Der Relativpronomen passt sich an das Nomen an (Kasus, Genus, Numerus).",
    examples: "Das ist der Mann, der in Berlin wohnt. | Die Frau, die ich gesehen habe, war nett. | Das Buch, das ich lese, ist spannend.", tips: "Der Relativpronomen steht immer am Anfang des Relativsatzes." },
  { id: "a2-12", name: "Konjunktiv II", description: "Höflichkeitsform und irreale Wünsche", level: "A2", order: 27,
    explanation: "Der Konjunktiv II wird gebildet mit: würde + Infinitiv (oder Modalverben: könnte, müsste, sollte, wollte). Er drückt Höflichkeit, Wünsche oder irreale Bedingungen aus.",
    examples: "Ich hätte gerne einen Kaffee. | Könnten Sie mir helfen? | Wenn ich reich wäre, würde ich reisen. | Ich sollte mehr lernen.", tips: "Konjunktiv II von haben: hätte. von sein: wäre. von werden: würde. Modalverben: könnte, müsste, sollte, wollte, dürfte." },
  { id: "a2-13", name: "Verben mit Dativ", description: "helfen, danken, gratulieren, gefallen", level: "A2", order: 28,
    explanation: "Manche Verben verlangen immer den Dativ: helfen (to help), danken (to thank), gratulieren (to congratulate), gefallen (to please), passen (to fit).",
    examples: "Ich helfe dem Kind. (Dat.) | Danke dir! (Dat.) | Das gefällt mir. (Dat.) | Das passt mir. (Dat.)", tips: "Tipp: Bei 'gefallen' steht das Nomen auf Position 1: Das Buch gefällt mir (nicht: Mir gefällt das Buch)." },
  { id: "a2-14", name: "Adjektivdeklination nach Artikel", description: "Adjektive ändern ihre Endung je nach Artikel", level: "A2", order: 29,
    explanation: "Adjektive haben verschiedene Endungen je nachdem, welcher Artikel vor ihnen steht: nach bestimmtem Artikel (-e, -en), nach unbestimmtem (-er, -e, -es), ohne Artikel (-er, -e, -es).",
    examples: "der große Tisch (bestimmt) | ein großer Tisch (unbestimmt) | großer Tisch (ohne Artikel) | die große Lampe | eine große Lampe | große Lampe", tips: "Merke die Endung nach dem Artikel: bestimmt (-e, -en), unbestimmt (-er, -e, -es), ohne (-er, -e, -es)." },
  { id: "a2-15", name: "Partizip I und II als Adjektiv", description: "Partizipien als beschreibende Adjektive", level: "A2", order: 30,
    explanation: "Das Partizip I (gehend, lesend) beschreibt eine aktive Handlung. Das Partizip II (gegangen, gelesen) beschreibt eine passive Handlung oder ein Ergebnis.",
    examples: "Die lesende Frau (Partizip I) | Das gelesene Buch (Partizip II) | Der spielende Junge (Partizip I) | Das gespielene Spiel (Partizip II)", tips: "Partizip I: ge- + Verbstamm + -end. Partizip II: ge- + Verbstamm + -t/-en." },

  // ===== B1 =====
  { id: "b1-01", name: "Passiv Präsens", description: "werden + Partizip II", level: "B1", order: 31,
    explanation: "Das Passiv wird gebildet mit: werden (konjugiert) + Partizip II. Es betont die Handlung statt des Handelnden.",
    examples: "Das Buch wird gelesen. | Die Tür wird geöffnet. | Deutsch wird in vielen Schulen gelernt.", tips: "Agent mit 'von': Das Buch wird von dem Schüler gelesen." },
  { id: "b1-02", name: "Passiv mit Modalverben", description: "kann/muss/soll + werden + Partizip II", level: "B1", order: 32,
    explanation: "Das Passiv mit Modalverben drückt eine Notwendigkeit oder Möglichkeit aus.",
    examples: "Das muss gemacht werden. | Das kann nicht gemacht werden. | Das sollte überprüft werden.", tips: "Modalverb + werden + Partizip II: Das Buch muss gelesen werden." },
  { id: "b1-03", name: "Konjunktiv II (indirekte Rede)", description: "Bericht von Aussagen anderer", level: "B1", order: 33,
    explanation: "In der indirekten Rede wird der Konjunktiv II benutzt, um wiederzugeben, was jemand gesagt hat.",
    examples: "Er sagte, er hätte keine Zeit. | Sie meinte, sie würde kommen. | Er sagte, er sei krank.", tips: "Konjunktiv I ist formeller: Er sagte, er sei krank. Konjunktiv II: Er sagte, er hätte keine Zeit." },
  { id: "b1-04", name: "Konjunktiv I (indirekte Rede)", description: "Formelle indirekte Rede", level: "B1", order: 34,
    explanation: "Der Konjunktiv I wird in der formellen indirekten Rede benutzt: sein, habe, werde, könne, müsse, solle, wolle.",
    examples: "Er sagte, er sei krank. | Sie meinte, sie habe keine Zeit. | Er erklärte, er werde kommen.", tips: "Der Konjunktiv I sieht fast aus wie der Infinitiv: ich sei, du seist, er sei, wir seien, sie seien." },
  { id: "b1-05", name: "Infinitivkonstruktionen", description: "um...zu, ohne...zu, statt...zu", level: "B1", order: 35,
    explanation: "Infinitivkonstruktionen verbinden zwei Handlungen: um...zu (in order to), ohne...zu (without), statt...zu (instead of).",
    examples: "Ich lerne, um besser zu werden. | Er ging, ohne zu bezahlen. | Statt zu arbeiten, spielt er.", tips: "Der Infinitiv mit 'zu' steht am Satzende. Das Subjekt beider Handlungen muss gleich sein." },
  { id: "b1-06", name: "Nebensätze: dass, ob, wenn", description: "Erweiterte Nebensätze", level: "B1", order: 36,
    explanation: "'dass' (that) leitet einen objektiven Nebensatz ein. 'ob' (whether) leitet einen indirekten Fragesatz ein. 'wenn' (if) leitet einen Konditionalsatz ein.",
    examples: "Ich glaube, dass du recht hast. | Ich weiß nicht, ob er kommt. | Wenn es regnet, bleibe ich.", tips: "Im Nebensatz steht das Verb am Ende." },
  { id: "b1-07", name: "Konzessivsätze", description: "obwohl, obgleich, trotzdem", level: "B1", order: 37,
    explanation: "Konzessivsätze drücken einen Gegensatz aus: obwohl (although), obgleich (although), trotzdem (nevertheless).",
    examples: "Obwohl es regnet, gehe ich. | Trotzdem bleibt er optimistisch. | Obgleich er krank war, kam er.", tips: "'obwohl' im Nebensatz (Verb am Ende), 'trotzdem' im Hauptsatz." },
  { id: "b1-08", name: "Kausalsätze", description: "weil, da, denn", level: "B1", order: 38,
    explanation: "Kausalsätze geben einen Grund an: weil (because – am häufigsten), da (since – formell), denn (for – literarisch).",
    examples: "Ich bleibe zu Hause, weil ich krank bin. | Da es spät ist, gehe ich. | Er blieb, denn er hatte keine Wahl.", tips: "'weil' – Verb am Satzende. 'denn' – Verb direkt nach 'denn'." },
  { id: "b1-09", name: "Finalsätze", description: "damit, um...zu", level: "B1", order: 39,
    explanation: "Finalsätze drücken einen Zweck aus: damit (so that – Verb am Ende), um...zu (in order to – Infinitivkonstruktion).",
    examples: "Ich lerne, damit ich Deutsch kann. | Er geht zur Uni, um zu studieren. | Sie arbeitet, damit sie Geld verdient.", tips: "'damit' + Nebensatz (Verb am Ende). 'um...zu' + Infinitiv." },
  { id: "b1-10", name: "Temporalsätze", description: "als, wenn, nachdem, bevor, seitdem", level: "B1", order: 40,
    explanation: "Temporalsätze geben eine Zeit an: als (when – Vergangenheit), wenn (when/if – Gegenwart/Zukunft), nachdem (after), bevor (before), seitdem (since).",
    examples: "Als ich jung war, spielte ich viel. | Wenn ich frei habe, gehe ich wandern. | Nachdem ich gegessen habe, gehe ich. | Bevor ich gehe, rufe ich an.", tips: "'als' für einmalige Ereignisse in der Vergangenheit. 'wenn' für wiederholte Ereignisse." },
  { id: "b1-11", name: "Verben mit Präposition", description: "denken an, warten auf, sich freuen auf", level: "B1", order: 41,
    explanation: "Bestimmte Verben werden immer mit einer bestimmten Präposition benutzt. Das beeinflusst den Kasus (Akkusativ oder Dativ).",
    examples: "Ich denke an dich. (Akk.) | Ich warte auf den Bus. (Akk.) | Ich freue mich auf den Urlaub. (Akk.) | Ich interessiere mich für Musik. (Akk.)", tips: "Es gibt keine Regel – man muss die Verben mit Präpositionen auswendig lernen!" },
  { id: "b1-12", name: "Adjektivdeklination nach Pronomen", description: "mein, dein, sein, ihr + Adjektiv", level: "B1", order: 42,
    explanation: "Nach Possessivpronomen folgt die unbestimmte Adjektivdeklination: -er (maskulin), -e (feminin), -es (neutral), -en (Plural).",
    examples: "mein großer Hund | deine große Wohnung | sein neues Auto | unsere kleinen Kinder", tips: "Die Endung entspricht der nach 'ein/eine': mein→-er/-e/-es." },
  { id: "b1-13", name: "N-Deklination", description: "Der Student, den Studenten", level: "B1", order: 43,
    explanation: "Maskuline Nomen auf -e, -ant, -ent, -ist, -at, -ot bilden den Akkusativ und Dativ mit -n: der Student → den Studenten, dem Studenten.",
    examples: "Der Student lernt. (Nom.) | Ich sehe den Studenten. (Akk.) | Ich gebe dem Studenten ein Buch. (Dat.)", tips: "N-Deklination: Nur maskuline Nomen! Im Plural: die Studenten (Nom.) → die Studenten (Akk./Dat.)." },
  { id: "b1-14", name: "Reflexive Verben mit Akkusativ und Dativ", description: "sich (Akk.) und sich (Dat.)", level: "B1", order: 44,
    explanation: "Manche reflexive Verben verwenden den Akkusativ, andere den Dativ. Der Dativ zeigt an, wem etwas passiert.",
    examples: "Ich freue mich. (Akk.) | Ich dusche mir die Haare. (Dat.) | Ich wasche mir die Hände. (Dat.) | Ich bilde mir ein. (Akk.)", tips: "Akkusativ: sich (mich, dich, sich, uns, euch, sich). Dativ: sich (mir, dir, sich, uns, euch, sich)." },
  { id: "b1-15", name: "Komma bei Nebensätzen", description: "Regeln für Kommas in komplexen Sätzen", level: "B1", order: 45,
    explanation: "Kommas trennen Nebensätze vom Hauptsatz: Ich weiß, dass du kommst. Kommas trennen auch Aufzählungen: rot, blau und grün.",
    examples: "Ich weiß, dass du kommst. | Er sagte, er sei krank. | Das Buch ist groß, aber interessant.", tips: "KEIN Komma bei Nebensätzen mit 'als', 'bevor', 'nachdem', 'wenn', 'weil', 'dass', 'ob' – NUR am Ende des Nebensatzes." },

  // ===== B2 =====
  { id: "b2-01", name: "Plusquamperfekt Passiv", description: "war + worden + Partizip II", level: "B2", order: 46,
    explanation: "Das Plusquamperfekt Passiv wird gebildet mit: war + worden + Partizip II. Es beschreibt eine passive Handlung in der Vergangenheit.",
    examples: "Das Buch war gelesen worden. | Die Straße war gereinigt worden. | Das Essen war vorbereitet worden.", tips: "war + worden (nicht: geworden!)" },
  { id: "b2-02", name: "Futur II", description: "werden + Partizip II + haben/sein", level: "B2", order: 47,
    explanation: "Das Futur II wird gebildet mit: werden + Partizip II + haben/sein. Es drückt eine abgeschlossene Handlung in der Zukunft aus.",
    examples: "Ich werde gelernt haben. | Er wird angekommen sein. | Wir werden das Buch gelesen haben.", tips: "Futur II mit 'sein' für Bewegungsverben: angekommen sein, gegangen sein, gefahren sein." },
  { id: "b2-03", name: "Konjunktiv I Passiv", description: "Formelle indirekte Rede im Passiv", level: "B2", order: 48,
    explanation: "Der Konjunktiv I Passiv wird gebildet mit: sei/habe/werde + worden + Partizip II.",
    examples: "Er sagte, das Buch sei gelesen worden. | Sie meinte, die Straße sei gereinigt worden.", tips: "Konjunktiv I Passiv ist sehr formell und wird hauptsächlich in Zeitungen und offiziellen Texten benutzt." },
  { id: "b2-04", name: "Konjunktiv II Vergangenheit", description: "hätte...getan (irreale Vergangenheit)", level: "B2", order: 49,
    explanation: "Der Konjunktiv II der Vergangenheit wird gebildet mit: hätte/wäre + Partizip II. Er drückt bereute oder unrealisierte Handlungen aus.",
    examples: "Ich hätte mehr lernen sollen. | Er wäre gegangen, wenn er Zeit gehabt hätte. | Wir hätten das Buch kaufen sollen.", tips: "hätte + Partizip II (für Verben mit haben). wäre + Partizip II (für Verben mit sein)." },
  { id: "b2-05", name: "Nominalisierung", description: "Verben zu Nomen machen", level: "B2", order: 50,
    explanation: "Verben können zu Nomen umgewandelt werden: das Lernen (learning), das Lesen (reading), das Schreiben (writing).",
    examples: "Das Lesen macht Spaß. | Das Lernen ist wichtig. | Das Schreiben fällt mir leicht.", tips: "Nominalisierung: ge- + Verbstamm + -ung (Bildung), -heit (Freiheit), -keit (Möglichkeit), -schaft (Freundschaft), -nis (Erkenntnis)." },
  { id: "b2-06", name: "Partizipialkonstruktionen", description: "Partizipialattribute als Adjektive", level: "B2", order: 51,
    explanation: "Partizipialkonstruktionen geben zusätzliche Informationen über ein Nomen: der lesende Mann (Partizip I), das gelesene Buch (Partizip II).",
    examples: "Der lesende Mann ist mein Vater. | Das gelesene Buch ist spannend. | Die spielenden Kinder sind glücklich.", tips: "Partizip I: aktiv (gehend, lesend). Partizip II: passiv (gegangen, gelesen). Partizip II kann auch adjektivisch verwendet werden." },
  { id: "b2-07", name: "Relativsätze mit Präposition", description: "Der Mann, mit dem ich gesprochen habe", level: "B2", order: 52,
    explanation: "Relativsätze können mit Präpositionen gebildet werden: Der Mann, mit dem ich gesprochen habe. Die Frau, über die ich redete.",
    examples: "Der Mann, mit dem ich gesprochen habe, ist nett. | Die Frau, über die ich redete, war dort. | Das Buch, von dem ich erzählt habe, ist gut.", tips: "Die Präposition steht am Anfang des Relativsatzes. Das Relativpronomen folgt direkt danach." },
  { id: "b2-08", name: "Emphatische Satzstellung", description: "Betonung durch Wortstellung", level: "B2", order: 53,
    explanation: "Durch die Wortstellung kann man einen Satz betonen: Nie habe ich das gesehen! (Betonung auf 'nie'). Nicht nur das, sondern auch das.",
    examples: "Nie habe ich das gesehen! | Nur das ist wichtig. | Nicht nur das, sondern auch das.", tips: "Betonung durch Frontstellung: Adverbien, Verben oder andere Satzteile können an den Anfang gestellt werden." },
  { id: "b2-09", name: "Konzessivsätze mit trotz", description: "trotz + Dativ (trotzdem, trotzdessen)", level: "B2", order: 54,
    explanation: "'trotz' + Dativ drückt einen Gegensatz aus: Trotz des Regens gehe ich. 'Trotzdem' steht im Hauptsatz.",
    examples: "Trotz des Regens gehe ich. | Trotzdem bleibt er optimistisch. | Trotzdessen komme ich.", tips: "'trotzdem' = 'trotzdem' (trotzdem). 'trotzdessen' = 'trotz dessen' (trotzdem)." },
  { id: "b2-10", name: "Konsekutivsätze", description: "so...dass, solch...dass", level: "B2", order: 55,
    explanation: "Konsekutivsätze drücken eine Folge aus: so...dass (so...that), solch...dass (such...that).",
    examples: "Er ist so müde, dass er einschläft. | Das ist so gut, dass ich es empfehle. | Solch ein Buch habe ich noch nie gelesen.", tips: "'so' + Adjektiv + dass. 'solch' + Nomen + dass." },

  // ===== C1 =====
  { id: "c1-01", name: "Konjunktiv I Futur", description: "Formelle indirekte Rede in der Zukunft", level: "C1", order: 56,
    explanation: "Der Konjunktiv I Futur wird gebildet mit: werde + Partizip II. Er drückt eine formelle Prophezeiung oder Erwartung aus.",
    examples: "Er sagte, er werde morgen kommen. | Sie meinte, es werde regnen.", tips: "Konjunktiv I Futur ist sehr formell und wird hauptsächlich in offiziellen Texten und Zeitungen benutzt." },
  { id: "c1-02", name: "Erweitertes Partizip", description: "Partizipialattribute als erweiterte Adjektive", level: "C1", order: 57,
    explanation: "Erweiterte Partizipialattribute geben ausführliche Informationen über ein Nomen: der in Berlin lebende Mann, das von mir gelesene Buch.",
    examples: "Der in Berlin lebende Mann ist mein Freund. | Das von mir gelesene Buch ist spannend. | Die in Deutschland studierenden Studenten lernen viel.", tips: "Erweiterte Partizipialattribute stehen NACH dem Nomen (nicht davor wie einfache Adjektive)." },
  { id: "c1-03", name: "Inversion nach negativer Einleitung", description: "Subjekt und Verb werden vertauscht nach negativen Einleitungen", level: "C1", order: 58,
    explanation: "Nach negativen Einleitungen (nie, niemals, selten, kaum, nicht nur) werden Subjekt und Verb invertiert.",
    examples: "Nie habe ich das gesehen. | Selten war es so kalt. | Kaum hatte ich angerufen, kam er.", tips: "Inversion: Subjekt und Verb vertauschen sich nach negativen Adverbien am Satzanfang." },
  { id: "c1-04", name: "Konzessionsadverbien", description: "trotzdem, dennoch, nichtsdestotrotz, gleichwohl", level: "C1", order: 59,
    explanation: "Konzessionsadverbien drücken einen Gegensatz aus: trotzdem (nevertheless), dennoch (yet), nichtsdestotrotz (nonetheless), gleichwohl (however).",
    examples: "Es ist teuer, aber ich kaufe es trotzdem. | Er ist krank, dennoch arbeitet er. | Nichtsdestotrotz gehe ich.", tips: "Konzessionsadverbien stehen am Anfang des Hauptsatzes oder nach dem Verb." },
  { id: "c1-05", name: "Logische Konnektoren", description: "daraus folgt, demnach, infolgedessen", level: "C1", order: 60,
    explanation: "Logische Konnektoren drücken eine logische Schlussfolgerung aus: daraus folgt (therefore), demnach (consequently), infolgedessen (as a result).",
    examples: "Er ist krank, daraus folgt, dass er nicht kommt. | Das Wetter ist schlecht, demnach gehe ich nicht.", tips: "Logische Konnektoren stehen am Anfang des Satzes oder nach dem Verb." },
  { id: "c1-06", name: "Nominalstil vs. Verbalstil", description: "Substantivierung vs. Verbalkonstruktion", level: "C1", order: 61,
    explanation: "Der Nominalstil verwendet Substantive, wo der Verbalstil Verben verwendet: die Durchführung vs. durchführen, die Untersuchung vs. untersuchen.",
    examples: "Die Durchführung des Projekts ist wichtig. vs. Das Projekt durchzuführen ist wichtig. | Die Untersuchung der Daten ist notwendig. vs. Die Daten zu untersuchen ist notwendig.", tips: "Nominalstil ist typisch für akademische Texte. Verbalstil ist klarer und direkter." },
  { id: "c1-07", name: "Zustandspassiv", description: "sein + Partizip II (Zustand nach Handlung)", level: "C1", order: 62,
    explanation: "Das Zustandspassiv beschreibt den Zustand nach einer Handlung: Das Fenster ist geöffnet (Zustand). vs. Das Fenster wird geöffnet (Handlung).",
    examples: "Das Fenster ist geöffnet. (Zustand) | Die Tür ist geschlossen. (Zustand) | Das Buch ist gelesen. (Zustand)", tips: "Zustandspassiv: sein + Partizip II. Vorgangspassiv: werden + Partizip II." },
  { id: "c1-08", name: "Stilmittel und Rhetorik", description: "Anapher, Ellipse, Chiasmus", level: "C1", order: 63,
    explanation: "Stilmittel verstärken die Wirkung einer Aussage: Anapher (Wiederholung am Satzanfang), Ellipse (Auslassung), Chiasmus (Umkehrung).",
    examples: "Anapher: Ich komme, ich sehe, ich siege. | Ellipse: Wenn ich Zeit habe (→), komme ich. | Chiasmus: Nicht die Fehler sind das Problem, sondern die Fehler des Problems.", tips: "Anapher: Wiederholung am Satzanfang. Ellipse: Auslassung von Satzteilen. Chiasmus: AB → BA Struktur." },
  { id: "c1-09", name: "Komplexe Satzstrukturen", description: "Verschachtelte Nebensätze", level: "C1", order: 64,
    explanation: "Komplexe Satzstrukturen verwenden mehrere Nebensätze, die ineinander verschachtelt sind.",
    examples: "Ich glaube, dass er kommt, weil er gesagt hat, dass er Zeit hat. | Obwohl er krank ist, kommt er, weil er weiß, dass es wichtig ist.", tips: "Nicht mehr als 2-3 Nebensätze verschachteln – sonst wird der Satz unverständlich." },
  { id: "c1-10", name: "Formelle und informelle Sprache", description: "Unterschiede zwischen Schrift- und Umgangssprache", level: "C1", order: 65,
    explanation: "Formelle Sprache verwendet komplexere Satzstrukturen, gehobenere Vokabeln und vermeidet Umgangssprache.",
    examples: "Formell: Ich möchte Sie darüber informieren, dass... | Informell: Ich wollte dir sagen, dass... | Formell: Es ist anzunehmen, dass... | Informell: Man kann davon ausgehen, dass...", tips: "In formellen Texten: Konjunktiv verwenden, komplexe Satzstrukturen, gehobene Vokabeln." },
];
