export const sentencesA1 = [
  { text: "Essen wir!", translationEn: "Let's eat!", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Essen sie?", translationEn: "Are they eating?", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Vorm Essen?", translationEn: "Before eating?", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Niemand ißt.", translationEn: "No one is eating.", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Nichts essen!", translationEn: "Don't eat anything.", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Grüßt eure Familie!", translationEn: "Give my best regards to your family.", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Grüße deine Familie!", translationEn: "Give my best regards to your family.", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Sie sind Familie.", translationEn: "They're family.", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Familie ist wichtig.", translationEn: "Family is important.", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Sie haben Familie.", translationEn: "They have families.", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Familie ist Familie.", translationEn: "Family is family.", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Hat Tom Familie?", translationEn: "Does Tom have any family?", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Grüß deine Familie!", translationEn: "Say hi to your family!", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Hast du Familie?", translationEn: "Do you have family?", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Tom zahlt.", translationEn: "Tom is buying.", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Ich zahlte.", translationEn: "I paid.", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Bitte zahlen!", translationEn: "The check, please.", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Zahlst du?", translationEn: "Will you pay?", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Zahlen bitte.", translationEn: "May I have the check, please?", level: "A1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Wer zahlt?", translationEn: "Who's picking up the tab?", level: "A1", source: "Tatoeba (CC BY 2.0)" },
];
