export const sentencesC1 = [
  { text: "Seine Überlegungen sind extrem akademisch.", translationEn: "His thoughts are extremely academic.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Mädchen sind im Akademischen ehrgeiziger als Jungen.", translationEn: "Girls are more ambitious academically than boys.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Mein Interesse an Politik ist rein akademisch.", translationEn: "My interest in politics is strictly academic.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Wo hast du deinen akademischen Abschluss gemacht?", translationEn: "Where did you get your degree?", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Akademischer Betrug ist verbreiteter, als man meinen möchte.", translationEn: "Academic fraud is more common than you might think.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Akademischer Betrug ist weiter verbreitet, als du denkst.", translationEn: "Academic fraud is more common than you might think.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Ich erlangte einen akademischen Grad im letzten Jahr.", translationEn: "I graduated from university last year.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Die Universität verlieh ihm ihren höchsten akademischen Grad.", translationEn: "The university conferred its highest degree on him.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Haben Sie Erfahrung im Management?", translationEn: "Do you have any management experience?", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Die Verantwortlichkeit des Managements der Organisation steht zur Debatte.", translationEn: "The accountability of the management of the organization is held in question.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Seit der Krise spart das Management sogar beim Toilettenpapier ein.", translationEn: "Management has even cut back on toilet paper since the crisis.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Die Gespräche zwischen Arbeitern und Management kamen zu keinem eindeutigen Ergebnis.", translationEn: "The talk between labor and management yielded no definite results.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Das Management versuchte, die Belegschaft zu beschwichtigen indem sie ihr einen Bonus anbot.", translationEn: "Management tried to appease labor by offering them a bonus.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Herr Johnson war besorgt wegen der Geldbeträge, die durch sorgloses Management verloren gingen.", translationEn: "Mr Johnson was concerned about the amount of money that was being lost because of careless management.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Wird das Management wirklich unseren Bonus berücksichtigen oder war das nur ein Lippenbekenntnis?", translationEn: "Is management really going to consider our bonus, or was that just lip service?", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Wir sind der Ansicht, dass alle Aussagen, die keine in diesem Bericht enthaltenen Aussagen zu historischen Fakten sind, einschließlich bestimmter Aussagen zum \"Geschäft und Management-Lagebericht und Analyse der Finanz- und Ertragslage\", zukunftsgerichtete Aussagen darstellen können.", translationEn: "We believe that all statements other than statements of historical facts included in this report, including certain statements under \"Business\" and \"Management's Discussion and Analysis of Financial Condition and Results of Operations,\" may constitute forward-looking statements.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Die Ethik hat fließende Grenzen.", translationEn: "Ethics has fluid boundaries.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "„Ethik“ bedeutet die Richtlinien des Handelns.", translationEn: "Ethics means the rules of conduct.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Die Ethik ist ein Zweig der Philosophie.", translationEn: "Ethics is a branch of philosophy.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Die Ethik ist ein Zweig der Philosophie, der sich mit dem menschlichen Handeln befasst.", translationEn: "Ethics is a branch of philosophy that treats of human conduct.", level: "C1", source: "Tatoeba (CC BY 2.0)" },
];
