export const sentencesB2 = [
  { text: "Die Wirtschaft schrumpft.", translationEn: "The economy is in recession.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Die Wirtschaft verbessert sich.", translationEn: "The economy is improving.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Die chinesische Wirtschaft wächst schnell.", translationEn: "The Chinese economy is growing rapidly.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Der Handel hilft unserer Wirtschaft.", translationEn: "Commerce helps our economy.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Hohe Steuern schaden der Wirtschaft.", translationEn: "Higher taxes hurt the economy.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Der Wirtschaft geht es schlecht.", translationEn: "The economy is bad.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Wissenschaft macht Spaß.", translationEn: "Science is fun.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Kochen ist eine Wissenschaft.", translationEn: "Cooking is a science.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Wissenschaft ist keine Religion.", translationEn: "Science is not a religion.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Das ist keine Wissenschaft.", translationEn: "It's not rocket science.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Ich mag keine Wissenschaft.", translationEn: "I do not like science.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Wissenschaft ist Magie, die funktioniert.", translationEn: "Science is magic that works.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Die Wissenschaft prägt unseren Lebensstil.", translationEn: "Science builds our lifestyle.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Rechts abbiegen!", translationEn: "Turn right.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Bitte rechts abbiegen!", translationEn: "Please make a right turn.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Ich habe Rechte.", translationEn: "I have rights.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Tom ist rechts.", translationEn: "Tom is on the right.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Ihr hattet recht.", translationEn: "You guys were right.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Ganz recht, Kumpel!", translationEn: "Quite right, mate.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Ich hatte recht.", translationEn: "I was right.", level: "B2", source: "Tatoeba (CC BY 2.0)" },
];
