export const sentencesB1 = [
  { text: "Sie arbeiten.", translationEn: "They're working.", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Arbeiten wir!", translationEn: "Let's work.", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Arbeiten Sie?", translationEn: "Are you working?", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Gehe arbeiten!", translationEn: "Go to work.", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Geh arbeiten!", translationEn: "Go to work.", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Gute Arbeit!", translationEn: "Good work!", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Arbeit adelt.", translationEn: "Work ennobles the soul.", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Gesundheit.", translationEn: "Bless you.", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Gesundheit!", translationEn: "Bless you!", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Was ist Gesundheit?", translationEn: "What is health?", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Gesundheit über Wohlstand.", translationEn: "Health over wealth.", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "„Hatschi!“ „Gesundheit!“ „Danke!“", translationEn: "\"Achoo!\" \"Bless you!\" \"Thanks.\"", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Sport bedeutet Gesundheit.", translationEn: "Sports mean health.", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Auf deine Gesundheit!", translationEn: "To your health!", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Gesundheit ist alles.", translationEn: "Health means everything.", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Interessiert dich Politik?", translationEn: "Are you interested in politics?", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Politik nervt mich.", translationEn: "Politics annoys me.", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Politik ist Politik.", translationEn: "Politics is politics.", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Ich verabscheue Politik.", translationEn: "I abhor politics.", level: "B1", source: "Tatoeba (CC BY 2.0)" },
  { text: "Ich hasse Politik.", translationEn: "I hate politics.", level: "B1", source: "Tatoeba (CC BY 2.0)" },
];
