export const sentencesA2 = [
  { text: "Ich reise.", translationEn: "I travel.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Angenehme Reise!", translationEn: "Have a nice trip!", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Tom reist.", translationEn: "Tom travels.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Lange Reise?", translationEn: "Long journey?", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Ich reiste.", translationEn: "I was travelling.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Reisen bildet.", translationEn: "Traveling makes people knowledgeable.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Gute Reise!", translationEn: "Have a safe trip.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Schöne Reise!", translationEn: "Enjoy your trip.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Sie reiste herum.", translationEn: "She traveled around.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Wann öffnen die Banken?", translationEn: "What time do the banks open?", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Tom ging zur Bank.", translationEn: "Tom went to the bank.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Sie ging zur Bank.", translationEn: "She went to the bank.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Er ging zur Bank.", translationEn: "He went to the bank.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Ich ging zur Bank.", translationEn: "I went to the bank.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Wann schließt die Bank?", translationEn: "When does the bank close?", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Medien vergiften den Geist.", translationEn: "The media poison the spirit.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Maria ist ein Medium.", translationEn: "Mary is a psychic.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Er ist ein Medium.", translationEn: "He is a psychic.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Sie ist ein Medium.", translationEn: "She is a psychic.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
  { text: "Die Bedeutung sozialer Medien wächst.", translationEn: "Social media is growing in importance.", level: "A2", source: "Tatoeba (CC BY 2.0)" },
];
